=== adrianhrb/1DAW/lnd/Tareas/XML/agenda.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT agenda (contacto*) >
<!ELEMENT contacto (nombre,apellido+,teléfono,email?, direccion) >

<!ELEMENT nombre (#PCDATA) >
<!ELEMENT apellido (#PCDATA) >
<!ELEMENT teléfono (#PCDATA) >
<!ELEMENT email (#PCDATA) >

<!ELEMENT direccion (calle, numero, cp) >
<!ELEMENT calle (#PCDATA) >
<!ELEMENT numero (#PCDATA) >
<!ELEMENT cp (#PCDATA) >

<!ATTLIST telefono pais CDATA #REQUIRED >

=== adrianhrb/1DAW/lnd/Tareas/XML/agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
	<contacto>
		<nombre>Juan</nombre>
		<apellido>Rodriguez</apellido>
		<apellido>Santana</apellido>
		<telefono pais="España">+34658784523</telefono>
		<email>juanro@loquesea.com</email>
		<direccion>
			<calle>C/ Lechuga</calle>
			<numero>25</numero>
			<cp>303040</cp>
		</direccion>
	</contacto>
	
		<contacto>
		<nombre>Juan</nombre>
		<apellido>Rodriguez</apellido>
		<apellido>Santana</apellido>
		<telefono pais="España">+34658784523</telefono>
		<email>juanro@loquesea.com</email>
		<direccion>
			<calle>C/ Lechuga</calle>
			<numero>25</numero>
			<cp>303040</cp>
		</direccion>
	</contacto>
</agenda>
